.example_audit_base:
  image: node
  before_script:
    - cd examples/audit
    - npm ci
  cache:
    - key:
        files:
          - yarn.lock
      paths:
        - node_modules

test_example_audit_app:
  extends: .example_audit_base
  image: cypress/browsers:node16.18.0-chrome107-ff106-edge
  stage: Integration Test
  script:
    - npm run cypress:ci
  artifacts:
    when: always
    paths:
      - cypress/videos/**/*.mp4
      - cypress/screenshots/**/*.png
    expire_in: 1 day
